module.exports = {
  parser: 'babel-eslint',
  extends: 'airbnb',
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  globals: {
    __DEV__: true,
  },
  rules: {
    'react/no-multi-comp': 'off',
    'react/forbid-prop-types': 'off',
    'react/jsx-filename-extension': 'off',
    'react/prefer-stateless-function': 'off',
    'react/jsx-closing-bracket-location': [
      'error', {
        selfClosing: 'line-aligned',
        nonEmpty: 'after-props',
      },
    ],
    'react/destructuring-assignment': 'off',
    'react/jsx-one-expression-per-line': 'off',
    'react/forbid-foreign-prop-types': 'off',
    'react/jsx-wrap-multilines': 'off',
    'react/sort-comp': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-unresolved': 'off',
    'import/extensions': 'off',
    'jsx-a11y/label-has-for': 'off',
    'comma-dangle': ['error', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      // Trailing commas in functions are allowed only in ES8
      // https://github.com/eslint/eslint/issues/7809
      functions: 'never',
    }],
    'function-paren-newline': ['off'],
    'global-require': 'off',
    'indent': ['error', 2, { SwitchCase: 1 }],
    'max-len': [2, 100],
    'no-await-in-loop': 'off',
    'no-confusing-arrow': 'off',
    'no-console': 'error',
    'no-restricted-syntax': ['error', 'ForInStatement', 'LabeledStatement', 'WithStatement'],
    'no-return-assign': 'off',
    'no-unused-expressions': ['error', { allowTernary: true }],
    'no-use-before-define': 'off',
    'object-curly-newline': 'off',
    'operator-linebreak': 'off',
    'prefer-promise-reject-errors': 'off',
    'quote-props': ['error', 'consistent-as-needed'],
    'semi': ['error', 'never'],
    'tipsi/remove-event-listener': ['error'],
  },
  plugins: [
    'react',
    'tipsi',
  ],
}
